
[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
account_address = "0x4e84d281b3e8d5d78ca6eba482ab2899e9431389c725fd9bee8a8dee405b5e7"
keystore = "./deployments/keystore.json"
world_block = 3550819
world_address = "0x07791d923f7b3a906f5480e2cb5ba9e46ad24cf2492bd47b210458c863ef68c2"

[world]
name = "Dope Wars"
seed = "dope2seed"
description = "Dope Wars is an onchain adaptation of the classic arbitrage game Drug Wars, built by Cartridge in partnership with Dope DAO."
website = "https://dopewars.game/"
icon_uri = "file://assets/icon.png"
cover_uri = "file://assets/cover.png"
socials.x = "https://x.com/TheDopeWars"

[namespace]
default = "dopewars"

[migration]
skip_contracts = [
    "dopewars-devtools",
    "dopewars-paper_mock",
    "dopewars-vrf_provider_mock",
]
order_inits = [
    "dopewars-game",
    "dopewars-config",
    "dopewars-laundromat",
    "dopewars-decide",
    "dopewars-ryo",
    "dopewars-game_token_system_v0",
    "dopewars-settings_systems", 
]

[init_call_args]
"dopewars-ryo" = [
    "0x410466536b5ae074f7fea81e5533b8134a9fa08b3dd077dd9db08f64997d113",  # PAPER address
    "0x051fea4450da9d6aee758bdeba88b2f665bcbf549d2c61421aa724e9ac0ced8f", # vrf address
    "0x0248f76e72088853c3fE96CAd8F7f075c9e514B862A6e9a3D5957EA5522eBb6D", # treasury / multisig address
]
"dopewars-game_token_system_v0" = [
    "0x0248f76e72088853c3fE96CAd8F7f075c9e514B862A6e9a3D5957EA5522eBb6D", # creator address
    "0x036017E69D21D6D8c13E266EaBB73ef1f1D02722D86BDcAbe5f168f8e549d3cD", # token address (Denshokan address)
]


[writers]

# "dopewars" = [
#     "dopewars-game",
#     "dopewars-config",
#     "dopewars-laundromat",
#     "dopewars-decide",
#     "dopewars-ryo",
#     "dopewars-game_token_system_v0",
#     "dopewars-settings_systems", 
# ]

"dopewars-GameConfig" = [
    "dopewars-config",
    "dopewars-laundromat",
    "dopewars-ryo",
]

"dopewars-DrugConfig" = ["dopewars-config"]
"dopewars-LocationConfig" = ["dopewars-config"]
"dopewars-HustlerItemBaseConfig" = ["dopewars-config"]
"dopewars-HustlerItemTiersConfig" = ["dopewars-config"]
"dopewars-EncounterStatsConfig" = ["dopewars-config"]

"dopewars-Game" = ["dopewars-game", "dopewars-laundromat", "dopewars-decide"]
"dopewars-GameStorePacked" = ["dopewars-game", "dopewars-decide"]
"dopewars-RyoConfig" = ["dopewars-game", "dopewars-laundromat", "dopewars-ryo"]
"dopewars-Season" = ["dopewars-game", "dopewars-laundromat", "dopewars-ryo"]
"dopewars-SeasonSettings" = [
    "dopewars-game",
    "dopewars-laundromat",
    "dopewars-ryo",
]

"dopewars-SortedList" = ["dopewars-game", "dopewars-laundromat"]
"dopewars-SortedListItem" = ["dopewars-game", "dopewars-laundromat"]
"dopewars-RyoAddress" = ["dopewars-ryo"]

"dopewars-GameSettings" = ["dopewars-settings_systems"]
"dopewars-GameSettingsMetadata" = ["dopewars-settings_systems"]
"dopewars-SettingsCounter" = ["dopewars-settings_systems"]

# events
"dopewars-GameCreated" = ["dopewars-game"]
"dopewars-Traveled" = ["dopewars-game", "dopewars-decide"]
"dopewars-GameOver" = ["dopewars-game", "dopewars-decide"]
"dopewars-TradeDrug" = ["dopewars-game", "dopewars-decide"]
"dopewars-UpgradeItem" = ["dopewars-game", "dopewars-decide"]
"dopewars-HighVolatility" = ["dopewars-game", "dopewars-decide"]
"dopewars-TravelEncounter" = ["dopewars-game", "dopewars-decide"]
"dopewars-TravelEncounterResult" = ["dopewars-game", "dopewars-decide"]
#
"dopewars-NewSeason" = ["dopewars-laundromat"]
"dopewars-NewHighScore" = ["dopewars-laundromat"]
"dopewars-Claimed" = ["dopewars-laundromat"]

# bushido
"dopewars-TrophyProgression" = ["dopewars-game", "dopewars-laundromat", "dopewars-decide"]
"dopewars-TrophyCreation" = ["dopewars-ryo"]

"dopewars-GameToken" = ["dopewars-game", "dopewars-laundromat", "dopewars-decide", "dopewars-game_token_system_v0"]
"dopewars-RandomnessConfig" = ["dopewars-ryo"]


# items
"dopewars-DopewarsItemTier" = ["dopewars-config"]
"dopewars-DopewarsItemTierConfig" = ["dopewars-config"]

#
# libraries
#

[lib_versions]
"dopewars-DopewarsItems" = "0"
