rpc = "https://api.cartridge.gg/x/starknet/mainnet"

world_address = "0x07791d923f7b3a906f5480e2cb5ba9e46ad24cf2492bd47b210458c863ef68c2"

[indexing]
allowed_origins = ["*"]
pending = true
transactions = false
polling_interval = 1000
contracts = []

[events]
raw = true    
historical = [
    "dopewars-GameCreated",
    "dopewars-Traveled",
    "dopewars-GameOver",
    "dopewars-TradeDrug",
    "dopewars-HighVolatility",
    "dopewars-UpgradeItem",
    "dopewars-TravelEncounter",
    "dopewars-TravelEncounterResult",
    "dopewars-NewSeason",
    "dopewars-NewHighScore",
    "dopewars-Claimed",
    # bushido 
    "dopewars-TrophyCreation",
    "dopewars-TrophyProgression",
]
