rpc = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x027a27e814146de539ae428b4a9aecdd225707d8dacca2336443dc81ee78a476"

[server]
http_cors_origins = ["*"]

[indexing]
index_pending = true
polling_interval = 1000
contracts = [
    "erc721:0x02334dc9c950c74c3228e2a343d495ae36f0b4edf06767a679569e9f9de08776"
]

[events]
historical_events = [
    "dopewars-GameCreated",
    "dopewars-Traveled",
    "dopewars-GameOver",
    "dopewars-TradeDrug",
    "dopewars-HighVolatility",
    "dopewars-UpgradeItem",
    "dopewars-TravelEncounter",
    "dopewars-TravelEncounterResult",
    "dopewars-NewSeason",
    "dopewars-NewHighScore",
    "dopewars-Claimed",
    # bushido 
    "dopewars-TrophyCreation",
    "dopewars-TrophyProgression",
]